version: '3.9'
services: 
    web:
        build: .
        container_name: web_Login
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - .:/code
        depends_on:
            - db
    db:
        container_name: django-base
        image: mysql:8.0.25 
        ports:
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_USERNAME: administrator
            MYSQL_PASSWORD: 1234
            MYSQL_DATABASE: MDB
        volumes:
            - ./mysql:/var/lib/mysql