# Generated by Django 3.2.7 on 2021-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_date',
            field=models.DateField(blank=True),
        ),
    ]
