# Generated by Django 3.2.7 on 2021-11-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_user_password_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
